Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'CodeQ.LinkChecker': ['Modules']
    modules:
      management:
        submodules:
          link-checker:
            label: 'CodeQ.LinkChecker:Modules:module.label'
            description: 'CodeQ.LinkChecker:Modules:module.description'
            icon: 'fas fa-link'
            controller: CodeQ\LinkChecker\Controller\Backend\ModuleController
            resource: 'CodeQ.LinkChecker:Backend.Module'
            privilegeTarget: 'CodeQ.LinkChecker:Backend.Module'
            additionalResources:
              styleSheets:
                - 'resource://CodeQ.LinkChecker/Public/Styles/link-checker.css'
    fusion:
      autoInclude:
        CodeQ.LinkChecker: true
